"""initial schema

Revision ID: 6ac299da54a2
Revises: 
Create Date: 2026-04-20 16:46:27.243921

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ac299da54a2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.CheckConstraint("market IN ('cn', 'us', 'hk')", name='ck_stocks_market'),
    sa.PrimaryKeyConstraint('symbol', 'market')
    )
    op.create_index('ix_stocks_market', 'stocks', ['market'], unique=False)
    op.create_table('daily_bars',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol', 'market'], ['stocks.symbol', 'stocks.market'], name='fk_daily_bars_stock'),
    sa.PrimaryKeyConstraint('symbol', 'market', 'date')
    )
    op.create_index('ix_daily_bars_date', 'daily_bars', ['date'], unique=False)
    op.create_table('fundamentals',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol', 'market'], ['stocks.symbol', 'stocks.market'], name='fk_fundamentals_stock'),
    sa.PrimaryKeyConstraint('symbol', 'market', 'as_of')
    )
    op.create_index('ix_fundamentals_as_of', 'fundamentals', ['as_of'], unique=False)
    op.create_table('watchlists',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol', 'market'], ['stocks.symbol', 'stocks.market'], name='fk_watchlists_stock', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_index('ix_fundamentals_as_of', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_daily_bars_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_index('ix_stocks_market', table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
